#! /bin/sh
### BEGIN INIT INFO
# Provides:          multipathd-udev-monitor
# Required-Start:    multipath-tools $syslog
# Required-Stop:     multipath-tools $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: multipathd-udev-monitor
# Description:
### END INIT INFO

PATH=/sbin
DAEMON=/sbin/multipathd_udev_monitor
NAME=multipathd_udev_monitor
DESC="Infinidat multipathd udev monitor utility"
DAEMON_OPTS=

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	start-stop-daemon --oknodo --start --quiet --background --make-pidfile --pidfile /var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS
	log_end_msg $?
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	start-stop-daemon --oknodo --stop --quiet --pidfile /var/run/$NAME.pid --exec $DAEMON
	log_end_msg $?
	;;
  restart|force-reload)
  	$0 stop
	$0 start
	;;
  *)
	N=/etc/init.d/multipath-tools
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
